# Part 1.1. Tensor Manipulation

In [0]:
import torch

## 1. Vector, Matrix and Tensor
`1D`를 vector, `2D`를 matrix, `3D`를 tensor라고 부른다. `4D`는 tensor를 위로, `5D`는 `4D`를 옆으로, `6D`는 `5D`를 위로 확장한 것이다.

![1-1.png](./img/1-1.png)

## 2. Pytorch Tensor Shape Convention
어떤 모양의 tensor 든 간에 `1D`는 **batch size** 즉, 데이터의 개수를 말한다. 그리고 `2D`부터 해당 데이터가 어떻게 생겼는지를 설명한다. 

* `2D Tensor` : $|t| = (batch size, dim)$ 데이터 개수가 batch size만큼 있으며, 차원(=벡터의 크기)는 dim이다.
* `3D Tensor Vision` : $|t| = (batch size, width, height)$ 데이터 개수가 batch size만큼 있으며, 이미지의 너비가 width, 높이가 height이다.
* `3D Tensor NLP` : $|t| = (batch size, length, dim)$ 데이터 개수가 batch size만큼 있으며, 문장의 길이가 length이며, 각 단어의 차원은 dim이다.

## 3. Pytorch Tensor
* `dim()` : 차원
* `shape`, `size()` : 모양

In [2]:
# 1차원 벡터
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])
print(t[:])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])
tensor([0., 1., 2., 3., 4., 5., 6.])


2차원 부터는 인덱스 안에 `:`이 있다면 해당 차원을 없앤다. 즉, 한 차원을 줄인다고 받아들이면 쉽다.

In [3]:
# 2차원 행렬
t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]])

print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])
print(t[1, :])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([4., 5., 6.])


## 4. Broadcasting
연산 시에 크기(=모양)이 다르다면 자동적으로 사이즈를 맞춰주는 기능을 말한다.

In [4]:
m1 = torch.FloatTensor([[3, 3]])  # |m1| = (1, 2)
m2 = torch.FloatTensor([[2, 2]])  # |m2| = (1, 2)
print(m1 + m2)

tensor([[5., 5.]])


In [5]:
m1 = torch.FloatTensor([[1, 2]])  # |m1| = (1, 2)
m2 = torch.FloatTensor([3])       # |m2| = (1, ) -> (1, 2)
print(m1 + m2)

tensor([[4., 5.]])


In [6]:
m1 = torch.FloatTensor([[1, 2]])    # |m1| = (1, 2) -> (2, 2)
m2 = torch.FloatTensor([[3], [4]])  # |m2| = (2, 1) -> (2, 2)
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 5. Multiplication vs Matrix Multiplication
* `a.matmul(b)` : 행렬의 내적 즉, dot production
* `a.mul(b)` : element-wise 곱셈

In [0]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])  # |m1| = (2, 2)
m2 = torch.FloatTensor([[1], [2]])        # |m2| = (2, 1)

In [8]:
# matmul : 행렬의 내적
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [9]:
# mul : element-wise 곱셈
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])


## 6. Other Operators

### 6.1. Aggregate Operators
전체에 대한 연산을 진행할 수 있지만 각 축마다 연산을 진행할 수 있다. 이 때 `dim`이 0일 때, 1일 때 등이 어떤 축을 말하는 건지 헷갈릴 수 있는데 그 때는 **해당 연산을 통해서 해당 축을 없앤다**는 느낌으로 받아들이면 된다.

In [10]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t.size())

torch.Size([2, 3])


In [11]:
# mean : 평균
print(t.mean())         # 전체 요소에 대한 평균
print(t.mean(dim=0))    # 첫 번째 차원에 대한 평균 -> (1, 3)
print(t.mean(dim=1))    # 두 번째 차원에 대한 평균 -> (2, 1)
print(t.mean(dim=-1))   # 마지막 차원에 대한 평균

tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor([2., 5.])


In [12]:
# sum : 합
print(t.sum())          # 전체 요소에 대한 합
print(t.sum(dim=0))     # 첫 번째 차원에 대한 합 -> (1, 3)
print(t.sum(dim=1))     # 두 번째 차원에 대한 합 -> (2, 1)
print(t.sum(dim=-1))    # 마지막 차원에 대한 합

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor([ 6., 15.])


In [13]:
# max : 최대값 
print(t.max())

# dim을 입력으로 넣을시 반환값으로 최대값과 최대값의 위치를 반환
# 인덱스를 통해 각각에 접근할 수 있음
print(t.max(dim=0))   # 첫 번째 차원에 대한 합 -> (1, 3)
print(t.max(dim=1))   # 두 번째 차원에 대한 합 -> (2, 1)
print(t.max(dim=-1))  # 마지막 차원에 대한 합

tensor(6.)
torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))
torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))


### 6.2. View
`np.reshape`와 같은 기능을 한다. tensor의 모양을 변형할 수 있다. 변형된 tensor의 각 차원의 크기의 곱은 원래 tensor의 각 차원의 크기와 같다. 이를 통해 `-1`로 된 미지의 차원의 크기를 구할 수 있다. `-1`의 경우 가장 변동이 심한 차원 예를 들면, **batch size**와 같은 차원에 넣는다.


In [14]:
t = torch.FloatTensor([[[0, 1, 2],
                        [3, 4, 5]],
                       [[6, 7, 8],
                        [9, 10, 11]]])
print(t.size())

torch.Size([2, 2, 3])


In [16]:
tv1 = t.view([-1, 3])       # (4, 3) = 12
tv2 = t.view([-1, 1, 3])    # (4, 1, 3) = 12

print(tv1)
print(tv1.size())
print(tv2)
print(tv2.size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 6.3. Squeeze
어떤 차원의 크기가 1인 경우 해당 차원을 없애준다. `squeeze`는 단순히 1인 차원만 제거하므로 `view`처럼 변형되 tensor의 각 차원의 크기의 곱과 원래 tensor의 각 차원의 크기의 곱과 같다.

In [17]:
t = torch.FloatTensor([[[0], [1], [2]]])  # (1, 3, 1)

print(t)
print(t.size())

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])


In [18]:
print(t.squeeze())            # (3, )
print(t.squeeze().size())

tensor([0., 1., 2.])
torch.Size([3])


### 6.4. Unsqueeze
`squeeze`와 반대로 내가 원하는 차원에 1을 추가할 수 있다. 즉, 차원을 늘려준다.

In [20]:
t = torch.Tensor([0, 1, 2])   # (3, )

print(t)
print(t.size())

tensor([0., 1., 2.])
torch.Size([3])


In [22]:
print(t.unsqueeze(0))         # 첫 번째 차원에 추가 -> (1, 3)
print(t.unsqueeze(0).size())

print(t.unsqueeze(1))         # 두 번째 차원에 추가 -> (3, 1)
print(t.unsqueeze(1).size())

print(t.unsqueeze(-1))        # 마지막 차원에 추가  -> (3, 1)
print(t.unsqueeze(-1).size())

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 6.5. Type Casting
tensor 안의 요소들의 데이터 타입을 캐스팅 할 수 있다.
* `t.float()` : float 실수로 캐스팅
* `t.long()` : int 정수로 캐스팅

In [23]:
lt = torch.LongTensor([1, 2, 3, 4])
ft = torch.FloatTensor([1., 2., 3., 4.])

print(lt.float())
print(ft.long())

tensor([1., 2., 3., 4.])
tensor([1, 2, 3, 4])


### 6.6. Concatenate
이어붙이는 면의 차원이 같을 경우 tensor를 이어붙일 수 있다. `dim`을 통해 어디로 이어붙일지 설정할 수 있는데 해당 `dim`을 늘린다고 생각하면 된다.

In [25]:
ft1 = torch.FloatTensor([[1, 2], [3, 4]])   # (2, 2)
ft2 = torch.FloatTensor([[5, 6], [7, 8]])   # (2, 2)

rt1 = torch.cat([ft1, ft2], dim=0)          # (4, 2)
rt2 = torch.cat([ft1, ft2], dim=1)          # (2, 4)

print(rt1)
print(rt1.size())         
print(rt2)
print(rt2.size())

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


### 6.7. Stacking
`concatenate`를 더 편리하게 해준 함수이다. `dim`을 통해 어디로 쌓을지 지정할 수 있으며, default값은 0이다.

In [28]:
ft1 = torch.FloatTensor([1, 4])     # (2, )
ft2 = torch.FloatTensor([2, 5])     # (2, )
ft3 = torch.FloatTensor([3, 6])     # (2, )

print(torch.stack([ft1, ft2, ft3]))           # (3. 2)
print(torch.stack([ft1, ft2, ft3]).size())
print(torch.stack([ft1, ft2, ft3], dim=1))    # (2, 3)
print(torch.stack([ft1, ft2, ft3], dim=1).size())

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


### 6.8. Ones and Zeros
입력으로 받는 tensor의 크기의 새로운 tensor를 생성하여 `ones_like`는 1로, `zeros_like`는 0으로 초기화시킨다.

In [29]:
ft = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

print(ft)
print(ft.size())

tensor([[0., 1., 2.],
        [2., 1., 0.]])
torch.Size([2, 3])


In [30]:
print(torch.ones_like(ft))
print(torch.zeros_like(ft))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 6.9. In-place Operation
연산 결과를 다른 변수가 아닌 원래 변수에 반영을 하고 싶다면 해당 operator 뒤에 `_`를 붙이면 된다.

In [31]:
print(ft.mul(2.))
print(ft)
print(ft.mul_(2.))
print(ft)

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
